service: camelot-sls-service 

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-api-gateway-throttling
package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

# DRY constants: define all compound/generated names in one place
# Override args are: .. defaults:
# --app_acroym          signed-uploader
# --s3_bucket           self:custom.app_acronym
# --s3_key_base         self:custom.stage
# --region              us-west-2
# --stage               dev 
# --deletion_policy     delete
custom:
  app_acronym: camelot_sls 
  default_stage: dev
  stage: ${opt:stage, self:custom.default_stage}
  stack_name: ${self:custom.app_acronym}-${self:custom.stage}
  region: ${opt:region, self:provider.region}
  aurora_cluster_arn: "arn:aws:rds:${self:custom.region}:472965085233:cluster:albion-serverless"
  secret_arn: "arn:aws:secretsmanager:${self:custom.region}:472965085233:secret:prod/camelot/albion-serverless-iINkbR"
  pythonRequirements:
    dockerizePip: non-linux 
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 20
  # DB parameters
  auroraUsername: postgres

resources:
  Resources:
    auroraDbCredentials:
      Type: AWS::SecretsManager::Secret
      Properties:
        Description: 'Credentails for the Aurora DB'
        GenerateSecretString:
            SecretStringTemplate: '{"username": "${self:custom.auroraUsername}"}'
            GenerateStringKey: 'password'

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  stage: ${opt:stage, self:custom.default_stage}
  timeout: 25
  logs:
    restApi: true
  environment:
    REGION: ${self:custom.region}
    AURORA_CLUSTER_ARN: ${self:custom.aurora_cluster_arn}
    SECRET_ARN: ${self:custom.secret_arn}
functions:
  add_player:
    handler: add_player.lambda_handler
    name: ${self:custom.stack_name}-AddPlayer
    description: AddPlayer method
    events:
      - http:
          path: players
          method: post
          cors: true
          integration: lambda-proxy
  get_game:
    handler: get_game.lambda_handler
    name: ${self:custom.stack_name}-GetGame
    description: GetGame method
    events:
      - http:
          path: games/{gameId}
          method: get
          cors: true
          integration: lambda-proxy
  get_outcomes:
    handler: get_outcomes.lambda_handler
    name: ${self:custom.stack_name}-GetOutcomes
    description: GetOutcomes method
    events:
      - http:
          path: outcomes
          method: get
          cors: true
          integration: lambda-proxy
  get_players:
    handler: get_players.lambda_handler
    name: ${self:custom.stack_name}-GetPlayers
    description: GetPlayers method
    events:
      - http:
          path: players
          method: get
          cors: true
          integration: lambda-proxy
  get_roles:
    handler: get_roles.lambda_handler
    name: ${self:custom.stack_name}-GetRoles
    description: GetRoles method
    events:
      - http:
          path: roles
          method: get
          cors: true
          integration: lambda-proxy
  get_scores:
    handler: get_scores.lambda_handler
    name: ${self:custom.stack_name}-GetScores
    description: GetScores method
    events:
      - http:
          path: scores 
          method: get
          cors: true
          integration: lambda-proxy
  record_game:
    handler: record_game.lambda_handler
    name: ${self:custom.stack_name}-RecordGame
    description: RecordGame method
    events:
      - http:
          path: games
          method: post
          cors: true
          integration: lambda-proxy
  delete_player:
    handler: delete_player.lambda_handler
    name: ${self:custom.stack_name}-DeletePlayer
    description: DeletePlayer method
  bootstrap:
    handler: bootstrap.lambda_handler
    name: ${self:custom.stack_name}-Bootstrap
    description: Bootstrap method
